spring:
  application:
    name: sentence-service
  config:
    import: configserver:http://localhost:8001

server:
  port: 8005

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    circuitbreakers:
      enabled: true

feign:
  circuitbreaker:
    enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
  instances:
    adjectiveClientCircuitBreaker:
      baseConfig: default
    articleClientCircuitBreaker:
      baseConfig: default
    nounClientCircuitBreaker:
      baseConfig: default
    subjectiveClientCircuitBreaker:
      baseConfig: default
    verbClientCircuitBreaker:
      baseConfig: default
