spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harumamburu/springCloudNine
          searchPaths: cloudConfig
  rabbitmq:
    addresses: 192.168.99.100:5672

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
