server:
  port: 8020

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://config-server:8001
  rabbitmq:
    addresses: rabbit-mq:5672

management:
  endpoints:
    web:
      exposure:
        include: health,info
